services:
  producer:
    container_name: producer
    build:
      context: ./producer
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge